### ISSUE TITLE
Use a GitHub Actions workflow for continuous integration

### ISSUE THREAD

**Issue by sidneymau** [LSSTDESC/psf-weather-station#3]
Create a GitHub Actions workflow to enable continuous integration of psf-weather-station.

Here's an first pass at this. This action will attempt to install psf-weather-station for python version 3.6, 3.7, 3.8, 3.9 on a recent ubuntu environment.
```
name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install psf-weather-station
        run: |
          python setup.py install
```
This would be in the file `.github/workflows/test.yaml`.
